Pullbranch
wslyvh/useWeb3 pull request #101
Opened 2023-04-10 14:42 UTC by JanetMo

Hello,
I tried to add several resources from my personal web3-resources list. 
Hope there is something helpful amongst them. (-:

2023-04-11 15:57 UTC, wslyvh requested changes
Awesome! This is a great list! Thanks for taking the time to submit all of these. 

Left a few comments, but happy to merge/add most of these

2023-04-11 15:57 UTC, wslyvh commented on content/guides/defi-developer-roadmap.md
duplicate

2023-04-11 15:57 UTC, wslyvh commented on content/earn/pointer.md
no longer active

2023-04-11 15:57 UTC, wslyvh commented on content/courses/devpill.md
duplicate. Listed under websites

2023-04-11 15:57 UTC, wslyvh commented on content/websites/kernel-resources.md
You added Kernel community above. I'd prefer that one and consider this as a duplicate.

2023-04-11 17:06 UTC, JanetMo commented
Sure, feel free to add what fits. 
The page is a great initiative!

2023-04-11 17:15 UTC, JanetMo commented
Or should I delete the commented ones? 
It's my first time doing a pull request 🙈 (-:

2023-04-11 19:41 UTC, wslyvh commented
> Or should I delete the commented ones? It's my first time doing a pull request see_no_evil (-:

That's great. Always nice to see first-time contributions :) 

If you feel like it, please go ahead an update the PR. 
In this case it's not too much work, but it's more common to have a PR ready to merge without requiring changes. 
But happy to help if you need any

2023-04-12 10:33 UTC, JanetMo commented
Thanks, hope it's fine now (-:

2023-04-15 10:40 UTC, merged

2023-04-15 10:42 UTC, wslyvh commented
Amazing.. Merged! Thanks again for contributing :)

2023-04-16 10:12 UTC, JanetMo commented
You`re welcome! I'll check once in a time if I find something to add. 

Look forward to the development of the page.  (-: